### ISSUE TITLE
Guidelines for making our pages pretty

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/kubernetes-docs#49]
Hi @evilnick ,

First of all let me apologize if you have already talked about these and I missed it. A couple of questions on the docs style:

- Is there a recommended high level page structure eg Start with "#page title" end with "#links"/"#conclusions"/"#next steps"
- I see when writing we are using "you have to run this", "your cluster" vs "we run" , "our cluster", I think this is worth mentioning.
- When do we use capital letters on the title/subtitles? We mostly use capital letters only when it is a product name for example "Ceph storage", but I also see "Helm Chart" I guess "Run conjure-up" and "etcd" are fine because they are written in lowercase. I wonder if we should write microk8s always with a lowercase "m".
- Do we start our pages with a header? https://github.com/juju-solutions/kubernetes-docs/blob/master/pages/k8s/ceph.md vs https://github.com/juju-solutions/kubernetes-docs/blob/master/pages/k8s/scaling.md
- Do we ignore the headers on each page?
```
---
wrapper_template: "base-docs.html"
markdown_includes:
  nav: "shared/_side-navigation.md"
context:
  title: "Ceph storage"
  description: How to get Ceph deployed and related to Kubernetes in order to have a default storage class. This allows for easy storage allocation.
keywords: quickstart
tags: [getting_started]
sidebar: k8smain-sidebar
permalink: ceph.html
layout: [base, ubuntu-com]
toc: False
---
```
Should the "title" match the first header of the page we are writting and/or the file name? Are tags & keywords used? How? What tags do we have defined?
- Line breaks? We do not do the text wrapping ourselves, right? (it a coder's habit)
- Any guidelines on the screenshots? I see screenshots of the desktop, of a window and of a window section. Any guidelines on what the resolution/format of the images should be?   

I am asking here through an issue so other team members are aware.

I am sorry if some of the questions sound... naive. :)

Cheers
